import {mountScene} from './scene3d.js?v=20260913-lab1';
import {createEngineeringModel} from './engineering-models3d.js?v=20260913-lab1';

const catalog=[
 {id:'verify',name:['배포 전 검증','Validate before release'],value:['문제가 있는 모델은 운영에 들어오지 않도록.','Keep an unready model out of production.'],tag:'01 / RELEASE CONFIDENCE',source:'sAI',
  why:['새 모델이 만들어졌다는 사실만으로 현장에 적용할 수는 없습니다. 안전성·부하·품질 기준을 통과하는 과정이 먼저입니다.','A new model is not automatically ready for the field. Security, load and quality checks must come first.'],
  outcome:['통과 여부가 배포를 결정합니다. 검증에서 탈락해도 기존 운영 모델은 계속 동작합니다.','Release follows the validation decision. A rejected candidate leaves the existing production model running.'],
  steps:[
   [['검증 대기','Candidate'],['새 모델을 운영과 분리합니다','Separate the candidate from production'],['왼쪽의 새 모델이 검증 경로에 진입합니다. 오른쪽 운영 모델의 요청 처리는 계속됩니다.','The candidate enters the test path on the left. The production model on the right keeps serving requests.']],
   [['검증 게이트','Test gates'],['보안·부하·품질을 차례로 확인합니다','Check security, load and quality'],['세 개의 게이트는 배포 전 검증 항목입니다. 통과 여부를 확인한 뒤 다음 단계로 이동합니다.','The three gates represent pre-release checks. Advancement depends on meeting the agreed criteria.']],
   [['미달 모델 차단','Reject'],['기준 미달 모델은 별도 경로로 빠집니다','A failed candidate is held back'],['주황색 모델이 운영 경로에서 분리됩니다. 자가평가·불확실성 보정 기준을 만족하지 못하면 배포하지 않는 원리입니다.','The amber candidate leaves the release path. Models below the self-evaluation and uncertainty criteria are held back.']],
   [['통과 모델 적용','Release'],['검증을 통과한 모델만 운영에 적용합니다','Only a validated candidate is released'],['이 장면은 재검증을 통과한 별도 후보의 배포를 보여줍니다. 검증 실패를 건너뛰어 배포하는 흐름이 아닙니다.','This scene shows a separate candidate after successful revalidation. A failed check is never bypassed.']]
  ]},
 {id:'select',name:['필요한 데이터만 학습','Learn from the right data'],value:['데이터는 많게보다, 배울 가치가 있게.','Collect what the model can learn from.'],tag:'02 / SELECTIVE INTELLIGENCE',source:'s14',
  why:['모든 원본을 전송하면 네트워크와 저장 공간을 먼저 소비합니다. 현장에서 처리할 데이터와 더 배워야 할 데이터를 구분합니다.','Uploading every raw input consumes network and storage. Separate data that can be handled locally from cases that need learning.'],
  outcome:['일상적인 추론은 엣지에서 마치고, 모호한 사례는 판정·라벨링을 거쳐 다음 학습에 활용합니다.','Routine inference stays at the edge. Ambiguous cases become learning material after review and labelling.'],
  steps:[
   [['현장 입력','Field input'],['카메라 데이터가 엣지로 모입니다','Field inputs reach the edge'],['작은 타일은 현장에서 들어오는 데이터입니다. 전체를 곧바로 학습 서버에 올리지 않습니다.','The small tiles represent field inputs. They are not all uploaded to a learning server.']],
   [['불확실성 분리','Separate'],['확실한 결과와 모호한 사례를 나눕니다','Separate routine and uncertain cases'],['청록색은 현장 처리, 주황색은 추가 판단이 필요한 Yellow Point를 뜻합니다.','Cyan indicates local processing. Amber identifies Yellow Points requiring further review.']],
   [['선별 수집','Select'],['주황색 사례만 학습 경로로 이동합니다','Only selected cases take the learning path'],['위쪽의 학습 경로와 아래쪽의 현장 결과 경로가 분리됩니다. 모호한 사례는 판정과 라벨을 보완합니다.','The upper learning path is separate from the lower local-result path. Selected cases receive review and labels.']],
   [['학습 환류','Feedback'],['현장 판정이 다음 학습의 재료가 됩니다','Field decisions inform the next training cycle'],['유용한 사례를 축적하면서 일상적인 현장 처리는 이어집니다. 타일 개수는 원리를 설명하는 예시입니다.','Useful cases accumulate while routine processing continues. The tile count is illustrative, not a measured sampling ratio.']]
  ]},
 {id:'swap',name:['운영을 잇는 모델 교체','Update without stopping'],value:['배우는 동안에도, 바꾸는 순간에도.','Keep serving while learning and updating.'],tag:'03 / OPERATIONAL CONTINUITY',source:'sAI',
  why:['교체를 위해 서비스를 멈추는 대신, 새 모델을 별도로 준비하고 요청의 경로를 전환합니다. 기준 모델은 복구를 위해 보존합니다.','Prepare the new model separately, then switch the request path. Preserve the baseline so there is a way back.'],
  outcome:['새 모델 준비 → 경로 전환 → 상태 관찰. 문제가 생기면 보존한 기준 모델로 되돌리는 안전장치를 함께 둡니다.','Prepare, switch and observe. If the new model fails the operating criteria, restore the preserved baseline.'],
  steps:[
   [['기존 모델 운영','Serve'],['A 슬롯이 현장 요청을 처리합니다','Slot A serves field requests'],['연속해서 흐르는 청록색 신호는 운영 요청입니다. 기준 모델은 그대로 유지됩니다.','The continuous cyan signals represent serving requests. The baseline model remains available.']],
   [['새 모델 준비','Prepare'],['B 슬롯에 새 모델을 준비합니다','Prepare the new model in slot B'],['새 모델이 별도 슬롯에 들어옵니다. 준비 중에도 요청은 A 슬롯으로 흐릅니다.','The new model enters the separate slot. Requests still flow through A while B is prepared.']],
   [['요청 경로 전환','Switch'],['요청이 준비된 B 슬롯으로 이동합니다','Route requests to the prepared slot B'],['아래쪽 경로로 바뀌어도 요청의 흐름은 이어집니다. 기존 모델은 즉시 제거하지 않습니다.','Requests follow the lower path without losing continuity. The old model is not immediately removed.']],
   [['문제 시 롤백','Rollback'],['기준 미달을 감지하면 A로 복귀합니다','Restore A if the new model falls short'],['복구 상황을 보여주는 예시입니다. 요청 경로가 보존된 기준 모델로 돌아오는 것을 확인해 보세요.','This is a recovery example. Watch requests return to the preserved baseline model.']]
  ]},
 {id:'edge',name:['엣지에 맞춘 경량화','Fit intelligence to the edge'],value:['현장 가까이에서 판단할 수 있도록.','Bring decisions closer to the field.'],tag:'04 / EDGE EFFICIENCY',source:'s15',
  why:['엣지 장치의 메모리와 연산 자원은 제한적입니다. 모델을 줄이는 것과 함께 필요한 품질이 유지되는지도 확인해야 합니다.','Edge devices have limited memory and compute. Reducing a model must go hand in hand with checking its required quality.'],
  outcome:['작아진 모델이 현장 장치에 배치되고, 입력부터 추론 결과까지의 경로가 현장 가까이에서 완성됩니다.','The optimised model is deployed on the field device, bringing the input-to-result path closer to operations.'],
  steps:[
   [['원본 모델','Source'],['원본 모델의 자원 부담을 확인합니다','Start with the source model'],['큰 블록 묶음은 원본 모델이 요구하는 자원을 표현합니다. 실제 신경망의 구조나 크기를 재현한 것은 아닙니다.','The large block array represents the source model’s resource footprint, not its literal network structure.']],
   [['모델 최적화','Optimise'],['모델을 줄이고 품질을 검증합니다','Reduce the model and verify quality'],['블록이 줄어들면서 최적화된 모듈이 나타납니다. 용량 절감만으로 배포를 승인하지 않습니다.','The block array contracts as the optimised module appears. A smaller size alone does not authorise release.']],
   [['장치 배치','Deploy'],['최적화된 모델이 엣지 엔진에 들어갑니다','Deploy into the edge engine'],['작아진 모듈이 오른쪽 장치에 배치됩니다. 현장 장치와 모델의 호환성을 함께 확인합니다.','The compact module moves into the device on the right. Model and device compatibility must also be verified.']],
   [['현장 추론','Infer locally'],['입력에서 결과까지, 현장에서 처리합니다','Process field inputs near their source'],['센서 입력이 엣지 엔진을 거쳐 결과로 이어집니다. 45ms는 기존 공개 지표이며 장치·모델에 따라 달라집니다.','Sensor inputs pass through the edge engine to the result. The published 45ms figure depends on the model and device.']]
  ]}
];

const english=()=>document.documentElement.lang==='en';
const pick=pair=>pair[english()?1:0];
function el(tag,className,html=''){const n=document.createElement(tag);n.className=className;n.innerHTML=html;return n;}
function initialize(){
 const grid=document.querySelector('.tech-grid'),pane=grid?.closest('.technology-page-content');if(!pane)return;
 pane.classList.add('engineering-page');
 const intro=pane.querySelector('.section-intro');
 const lab=el('section','engineering-lab',`<header class="eng-heading"><div><span class="eng-kicker">ZIEWCORE / ENGINEERING IN MOTION</span><h2></h2></div><p></p></header><div class="eng-topics" role="tablist"></div><div class="eng-theater" role="tabpanel" id="engineering-panel"><div class="eng-visual"><div class="eng-stage-head"><span></span><b>3D / EXPLAINED</b></div><div class="eng-canvas"></div><div class="eng-scene-status"><span></span><strong></strong></div><div class="eng-controls"><small></small><button type="button" class="eng-pause"></button></div></div><div class="eng-narrative"><span class="eng-kicker"></span><h3></h3><p class="eng-why"></p><div class="eng-steps"></div><div class="eng-phase"><span></span><h4></h4><p></p></div><div class="eng-outcome"><b></b><p></p></div><div class="eng-bottom"><button type="button" class="eng-replay"></button><a target="_blank" rel="noopener"></a></div></div></div><p class="eng-note"></p>`);
 pane.prepend(lab);intro.classList.add('eng-original-intro');
 const specification=el('h3','eng-spec-heading');grid.before(specification);
 grid.querySelectorAll('.operation-notes').forEach(n=>n.open=true);
 const empty=grid.children[1].querySelector('.operation-labels');empty.innerHTML='<span>Edge inference</span><span>Yellow Point</span><span>Review &amp; label</span><span>Learning feedback</span>';
 let selected=0,phase=0,scene=null,mountedKey='',paused=matchMedia('(prefers-reduced-motion: reduce)').matches,manual=false,dialog=false,active=false;
 const host=lab.querySelector('.eng-canvas');
 catalog.forEach((data,index)=>{const b=el('button','eng-topic',`<span>0${index+1}</span><strong></strong><small></small>`);b.type='button';b.id=`eng-tab-${data.id}`;b.setAttribute('role','tab');b.setAttribute('aria-controls','engineering-panel');b.addEventListener('click',()=>{selected=index;phase=0;render();mount();});lab.querySelector('.eng-topics').append(b);});
 lab.querySelector('.eng-topics').addEventListener('keydown',event=>{const keys={ArrowRight:1,ArrowLeft:-1};let next;if(event.key in keys)next=(selected+keys[event.key]+4)%4;if(event.key==='Home')next=0;if(event.key==='End')next=3;if(next===undefined)return;event.preventDefault();lab.querySelectorAll('.eng-topic')[next].click();lab.querySelectorAll('.eng-topic')[next].focus();});
 for(let i=0;i<4;i++){const b=el('button','');b.type='button';b.addEventListener('click',()=>{phase=i;scene?.setPhase(i);renderPhase();});lab.querySelector('.eng-steps').append(b);}
 function sync(){scene?.setPaused(paused||dialog||!active,{manual});lab.querySelector('.eng-pause').textContent=pick(paused?['모션 재생 ▶','Play motion ▶']:['모션 일시정지 Ⅱ','Pause motion Ⅱ']);lab.querySelector('.eng-pause').setAttribute('aria-pressed',String(paused));lab.classList.toggle('eng-paused',paused||!active);}
 lab.querySelector('.eng-pause').addEventListener('click',()=>{paused=!paused;manual=true;sync();});
 lab.querySelector('.eng-replay').addEventListener('click',()=>{phase=0;paused=false;manual=true;sync();scene?.playSteps();renderPhase();});
 function renderPhase(){const data=catalog[selected],s=data.steps[phase];lab.dataset.phase=phase;lab.querySelectorAll('.eng-steps button').forEach((b,i)=>{b.textContent=`0${i+1} ${pick(data.steps[i][0])}`;b.setAttribute('aria-pressed',String(i===phase));});lab.querySelector('.eng-phase>span').textContent=`0${phase+1} / 04 — ${pick(s[0])}`;lab.querySelector('.eng-phase h4').textContent=pick(s[1]);lab.querySelector('.eng-phase p').textContent=pick(s[2]);lab.querySelector('.eng-scene-status>span').textContent=pick(['지금 보는 동작','WHAT YOU ARE SEEING']);lab.querySelector('.eng-scene-status strong').textContent=pick(s[1]);}
 function render(){const data=catalog[selected];lab.dataset.topic=data.id;lab.querySelector('.eng-heading h2').textContent=pick(['스스로 진화하는 AI.\n운영을 지키는 네 가지 설계.','AI that evolves.\nFour designs that protect operations.']);lab.querySelector('.eng-heading p').textContent=pick(['모델이 만들어진 다음이 기술의 시작입니다.\n수집·검증·교체·추론이 이어지는 이유를 직접 살펴보세요.','Engineering continues after a model is built.\nExplore how collection, validation, updates and inference connect.']);lab.querySelector('.eng-topics').setAttribute('aria-label',pick(['핵심 기술 선택','Choose an engineering capability']));lab.querySelectorAll('.eng-topic').forEach((b,i)=>{b.querySelector('strong').textContent=pick(catalog[i].name);b.querySelector('small').textContent=['VALIDATION','ACTIVE LEARNING','HOT-SWAP','EDGE ENGINE'][i];b.setAttribute('aria-selected',String(i===selected));b.tabIndex=i===selected?0:-1;});lab.querySelector('.eng-theater').setAttribute('aria-labelledby',`eng-tab-${data.id}`);lab.querySelector('.eng-stage-head>span').textContent=data.tag;lab.querySelector('.eng-narrative>.eng-kicker').textContent=pick(data.name);lab.querySelector('.eng-narrative>h3').textContent=pick(data.value);lab.querySelector('.eng-why').textContent=pick(data.why);lab.querySelector('.eng-outcome>b').textContent=pick(['그래서, 현장에서는','WHAT THIS MEANS IN PRACTICE']);lab.querySelector('.eng-outcome>p').textContent=pick(data.outcome);lab.querySelector('.eng-bottom a').href='/ai-briefing/';lab.querySelector('.eng-bottom a').textContent=pick(['기술 브리핑에서 더 보기 ↗','Explore the technical briefing ↗']);lab.querySelector('.eng-replay').textContent=pick(['전체 흐름 다시 보기 ↻','Replay the full flow ↻']);lab.querySelector('.eng-controls small').textContent=pick(['자동 단계 진행 · 드래그로 시점 조절','Automatic steps · Drag to explore']);lab.querySelector('.eng-note').textContent=pick(['작동 원리를 설명하는 3D 개념 시연입니다. 실제 운영 데이터나 실시간 검증 결과를 표시하지 않습니다.','An illustrative 3D explanation of the engineering mechanisms, not a live operational or validation feed.']);specification.textContent=pick(['핵심 설계와 공개 사양','Engineering details & published specifications']);renderPhase();sync();localizeCanvas();}
 function localizeCanvas(){const label=pick(catalog[selected].name)+' · '+pick(['작동 원리 3D. 방향키 또는 드래그로 둘러보기.','Illustrative 3D. Use arrow keys or drag to explore.']);host.querySelector('canvas')?.setAttribute('aria-label',label);const fallback=host.querySelector('.webgl-fallback');if(fallback){fallback.querySelector('span').textContent=pick(catalog[selected].value);fallback.querySelector('small').textContent=pick(['이 기기에서는 3D를 사용할 수 없습니다. 옆의 네 단계로 작동 과정을 확인하세요.','3D is unavailable on this device. Use the four steps to explore the mechanism.']);}}
 function mount(){active=window.ZiewisePages?.getCurrent()?.view==='engineering';if(active){const id=catalog[selected].id;if(!scene){scene=mountScene(host,{studioFloor:true,modelFactory:T=>createEngineeringModel(T,id),onPhase:p=>{phase=p;renderPhase();}});mountedKey=id;}else if(mountedKey!==id){mountedKey=id;scene.setProcess(T=>createEngineeringModel(T,id));}localizeCanvas();}sync();}
 window.addEventListener('ziewise:language',render);window.addEventListener('ziewise:pagechange',mount);window.addEventListener('ziewise:motion',e=>{paused=e.detail.paused;manual=e.detail.manual;sync();});window.addEventListener('ziewise:dialog',e=>{dialog=!!e.detail;sync();});window.addEventListener('pagehide',e=>{if(!e.persisted)scene?.dispose();});render();mount();
 initializePerformance();
}

function initializePerformance(){
 const dashboards=[...document.querySelectorAll('.perf-dashboard')],pane=dashboards[0]?.parentElement;if(!pane)return;pane.classList.add('performance-page');
 const compare=el('section','performance-comparison',`<header class="eng-heading"><div><span class="eng-kicker">ZIEWCORE / PERFORMANCE, IN CONTEXT</span><h2></h2></div><p></p></header><div class="perf-comparison-grid"><article class="compare-card model-comparison"><div class="compare-overline">01 / MODEL FOOTPRINT</div><h3></h3><div class="compare-result"><strong>96.25<small>%</small></strong><span></span></div><div class="comparison-bars"><div><span></span><b>1,200 MB</b><i style="--size:100%"></i></div><div><span>ZiewCore</span><b>45 MB</b><i style="--size:3.75%"></i></div></div><p></p></article><article class="compare-card network-comparison"><div class="compare-overline">02 / DATA TRANSFER</div><h3></h3><div class="compare-result"><strong>90<small>%</small></strong><span></span></div><div class="packet-comparison"><div><span></span><div class="packet-grid all-packets"></div><b>100</b></div><div><span></span><div class="packet-grid selected-packets"></div><b>10</b></div></div><p></p></article><article class="compare-card continuity-comparison"><div class="compare-overline">03 / SERVICE CONTINUITY</div><h3></h3><div class="compare-result"><strong>0<small>ms</small></strong><span></span></div><div class="continuity-track"><div><span></span><i class="broken-path"></i></div><div><span>Hot-Swap</span><i class="unbroken-path"></i></div></div><p></p></article></div><div class="comparison-table-heading"><h3></h3><button type="button" class="comparison-replay"></button></div><div class="comparison-table-wrap"><table><caption></caption><thead></thead><tbody></tbody></table></div><p class="performance-provenance"></p></section>`);
 pane.prepend(compare);for(let i=0;i<100;i++){compare.querySelector('.all-packets').append(el('i',''));compare.querySelector('.selected-packets').append(el('i',i<10?'transmitted':'retained'));}
 const rows=[
  [['모델 용량','Model size'],['원본 1.2GB','Source 1.2GB'],['경량 모델 45MB','Optimised 45MB'],['메모리·전송 부담 감소','Lower storage and transfer footprint'],['1GB=1,000MB 기준 용량 96.25% 감소. 기존 26:1은 근사 표기.','96.25% smaller using 1GB=1,000MB. Published 26:1 is approximate.']],
  [['데이터 전송','Data transfer'],['전체 전송량을 100으로 환산','Full transfer normalised to 100'],['90% 절감 시 전송량 10','10 transferred at 90% saving'],['선별 수집으로 업로드 부담 감소','Selective collection reduces uploads'],['기존 공개 절감률을 상대량으로 환산한 예시. 현장별 상이.','Illustration derived from the published saving, which varies by site.']],
  [['모델 교체','Model update'],['정지 후 교체하는 방식','Stop-and-replace workflow'],['준비 → 전환 → 상태 관찰','Prepare → switch → observe'],['운영 중 교체·문제 시 기준 모델 복귀','Update in operation; restore the baseline on failure'],['방식 비교. 특정 타사 중단시간을 가정하지 않음.','Workflow comparison; no assumed competitor downtime.']],
  [['엣지 추론','Edge inference'],['동일 조건 비교값 미공개','Matched baseline not published'],['공개 지연시간 45ms','Published latency: 45ms'],['입력 가까이에서 추론 처리','Inference close to the input'],['장치·모델·입력·동시 부하를 맞춰 비교해야 함.','Compare with matching device, model, input and concurrent load.']],
  [['검증·운영 기준','Validation & service'],['계약·테스트 조건에 따라 다름','Depends on test and contract conditions'],['100K+ 시뮬레이션 / 99.9% SLA','100K+ simulations / 99.9% SLA'],['배포 전 검증과 서비스 연속성 관리','Pre-release checks and continuity management'],['테스트 횟수와 SLA를 실시간 성공률로 해석하지 않음.','Test count and SLA are not live observed success rates.']]
 ];
 function render(){compare.querySelector('h2').textContent=pick(['숫자보다 명확한,\n운영의 차이.','Beyond the numbers.\nSee the operational difference.']);compare.querySelector('.eng-heading>p').textContent=pick(['모델은 얼마나 가벼워지고, 전송은 얼마나 줄어드는가.\n공개 지표를 같은 기준에 놓고 비교합니다.','How much smaller is the model? How much data is transferred?\nCompare the published figures on explicit, shared scales.']);
  const titles=[['같은 모델의 무게를 덜다','Reduce the model footprint'],['보내야 할 데이터만 남기다','Send the data that matters'],['교체 중에도 요청은 계속','Keep requests moving during updates']],results=[['용량 감소 · 산술 환산','smaller · calculated'],['공개 전송 절감률','published traffic saving'],['공개 모델 교체 중단시간','published update downtime']],notes=[['1.2GB → 45MB · 길이는 용량에 비례합니다. 정확도 유지 99.4%는 기존 공개 사양입니다.','1.2GB → 45MB · Bar lengths are proportional. 99.4% accuracy retention is a published specification.'],['한 칸은 상대 전송량 1을 뜻합니다. 100 → 10은 공개 절감률을 설명하기 위한 환산입니다.','Each cell represents one relative unit. 100 → 10 illustrates the published saving.'],['위는 정지 후 교체, 아래는 요청 경로 전환의 개념도입니다. 선의 길이는 시간을 의미하지 않습니다.','Top: stop and replace. Bottom: switch the serving path. Line length does not represent elapsed time.']];
  compare.querySelectorAll('.compare-card').forEach((card,i)=>{card.querySelector('h3').textContent=pick(titles[i]);card.querySelector('.compare-result>span').textContent=pick(results[i]);card.querySelector(':scope>p').textContent=pick(notes[i]);});compare.querySelector('.comparison-bars>div>span').textContent=pick(['원본 모델','Source model']);compare.querySelector('.packet-comparison>div:first-child>span').textContent=pick(['전체 전송','Full transfer']);compare.querySelector('.packet-comparison>div:last-child>span').textContent=pick(['선별 전송','Selected transfer']);compare.querySelector('.continuity-track>div>span').textContent=pick(['정지·교체','Stop & replace']);compare.querySelector('.comparison-table-heading h3').textContent=pick(['어떤 차이가 생기는지, 한눈에.','The difference, side by side.']);compare.querySelector('.comparison-replay').textContent=pick(['비교 다시 보기 ↻','Replay comparison ↻']);compare.querySelector('caption').textContent=pick(['공개 수치와 작동 방식 비교','Published figures and workflow comparison']);compare.querySelector('thead').innerHTML='<tr>'+[['비교 항목','Dimension'],['비교 기준','Reference'],['ZiewCore','ZiewCore'],['운영에서의 의미','Operational meaning']].map(x=>`<th scope="col">${pick(x)}</th>`).join('')+'</tr>';compare.querySelector('tbody').innerHTML=rows.map(row=>`<tr><th scope="row">${pick(row[0])}</th><td>${pick(row[1])}</td><td><strong>${pick(row[2])}</strong></td><td>${pick(row[3])}<small>${pick(row[4])}</small></td></tr>`).join('');compare.querySelectorAll('tbody tr').forEach(tr=>tr.querySelectorAll('td').forEach((td,i)=>td.dataset.label=pick([['비교 기준','Reference'],['ZiewCore','ZiewCore'],['운영에서의 의미','Operational meaning']][i])));compare.querySelector('.performance-provenance').textContent=pick(['기준: Ziewise 홈페이지·AI 브리핑의 기존 공개 사양. 실시간 계측 화면이 아닙니다. 동일 조건의 시험 보고서가 공개되지 않은 항목은 타사 성능 우위로 비교하지 않았습니다. 실제 성능과 SLA 적용 범위는 모델·장비·운영 및 계약 조건에 따라 확인해야 합니다.','Basis: specifications already published on the Ziewise website and AI briefing. This is not live telemetry. No competitor advantage is inferred where matched test reports are unavailable. Actual performance and SLA scope depend on model, hardware, operating and contract conditions.']);
  dashboards[0].querySelector('.perf-title').textContent=pick(['공개 성능 사양','Published performance specifications']);dashboards[0].querySelector('.perf-sub').textContent=pick(['개별 지표와 기존 공개값 · 비교 조건은 위 표를 참고하세요.','Individual published figures · See the comparison conditions above.']);dashboards[0].querySelector('.perf-meta').textContent=pick(['공개 지연시간 · 동일 조건 비교값 미공개','Published latency · No matched baseline published']);
 }
 let timer;function replay(){compare.classList.remove('comparison-playing');clearTimeout(timer);requestAnimationFrame(()=>requestAnimationFrame(()=>compare.classList.add('comparison-playing')));timer=setTimeout(()=>compare.classList.remove('comparison-playing'),6500);}
 compare.querySelector('.comparison-replay').addEventListener('click',replay);
 function state(){const active=window.ZiewisePages?.getCurrent()?.view==='performance';compare.classList.toggle('comparison-active',active);if(active)replay();}
 window.addEventListener('ziewise:language',render);window.addEventListener('ziewise:pagechange',state);window.addEventListener('pagehide',()=>clearTimeout(timer));render();state();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>queueMicrotask(initialize),{once:true});else queueMicrotask(initialize);
